config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/friends', to: 'users#friends' , id: 0
  get '/requests', to: 'users#requests'
  get '/outgoing', to: 'users#outgoing'
  get '/suggestions', to: 'users#suggestions'
  get '/add_avatar', to: 'users#add_avatar'
  get '/photos', to: 'users#photos', id: 0
  resources :users, only: [:show, :update] do
    member do
      get :friends
      get :photos
    end
#    collection do
#      get :suggestions
#    end
  end
  resources :friendships, only: [:create, :destroy, :update]
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments, only: [:create, :destroy, :update, :edit] do
    member do
      get :show_edit_comment_window, as: 'window'
    end
  end
  get 'show_edit_comment_window', to: 'comments#show_edit_comment_window'
  resources :likes, only: [:create, :destroy]
  resources :post_attachments
  get '/sign_in', to: 'users#sign_in'
  get '/get_comments', to: 'comments#get_comments'
  get '/newest', to: 'static_pages#newest'
end

app/models/user.rb
class User < ApplicationRecord
  include ApplicationHelper

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true

  has_many :active_requests, class_name:  "FriendRequest",
                             foreign_key: "requestor_id",
                             dependent:   :destroy
  has_many :passive_requests, class_name:  "FriendRequest",
                              foreign_key: "receiver_id",
                              dependent:   :destroy
  has_many :sent_requests, through: :active_requests, source: :receiver
  has_many :received_requests, through: :passive_requests, source: :requestor
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_post_relationships, class_name:  "Like",
                                    dependent:   :destroy
  has_many :liked_posts, through: :like_post_relationships, source: :post
  has_many :post_attachments, through: :posts
  has_attached_file :avatar, :default_url => "assets/images/:style/default_avatar.jpg", :styles => {
      :comment_thumb => "40x40#",
      :thumb => "60x60#",
      :small  => "300x300#",
      :medium => "400x400#" }
  validates_attachment :avatar, allow_nil: true, size: { in: 0..5.megabytes }, content_type: { content_type: /\Aimage/ }

  devise :omniauthable, :omniauth_providers => [:facebook]

  # after_update :update_redis

  def friend_request(other_user)
    sent_requests << other_user
  end

  def undo_friend_request(other_user)
    sent_requests.delete(other_user)
  end

  def pending_request?(other_user)
    if active = active_requests.find_by(receiver_id: other_user.id)
      !active.confirmed
    else
      false
    end
  end

  def awaiting_confirm?(other_user)
    if passive = passive_requests.find_by(requestor_id: other_user.id)
      !passive.confirmed
    else
      false
    end
  end

  def confirm_request(other_user)
    passive_requests.find_by(requestor_id: other_user.id).update_attributes(confirmed: true)
    friendships.create!(friend_id: other_user.id)
  end

  def undo_confirm_request(other_user)
    friendships.find_by(friend_id: other_user.id).destroy
    passive_requests.find_by(requestor_id: other_user.id).update_attributes(confirmed: false)
  end

  def deny_request(other_user)
    passive_requests.find_by(requestor_id: other_user.id).destroy
  end

  def unfriend(other_user)
    friendships.find_by(friend_id: other_user.id).destroy
    if active = active_requests.find_by(receiver_id: other_user.id)
      active.destroy
    elsif passive = passive_requests.find_by(requestor_id: other_user.id)
      passive.destroy
    end
  end

  def friend?(other_user)
    !friendships.find_by(friend_id: other_user.id).nil?
  end

  def unrelated?(other_user)
    requests = self.received_requests + self.sent_requests
    !requests.include?(other_user) and self != other_user
  end


#shortcut method to skip confirmation
  def friend(other_user)
    friendships.create!(friend_id: other_user.id)
  end

  def feed
    Post.includes(:user, :liked_users, :post_attachments).where("(user_id IN (?) OR user_id = ?)", friend_ids, id ).order(created_at: :desc)
  end

  def like(post)
    liked_posts << post
  end

  def unlike(post)
    liked_posts.destroy(post)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      user.fb_avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def avatar_present?
    avatar.present?
  end

  def avatar_url_thumb
    avatar.url(:thumb)
  end

  # def update_redis
  #   last_post = $redis.zrevrange("newest_posts", -1 ,-1)[0]
  #   last_id = $redis.zscore("newest_posts", last_post)
  #   self.posts.where("id >= #{last_id}").each do |post|
  #     remove_record_from_redis(post)
  #     add_record_to_redis(post)
  #   end
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def suggestions
    @user = current_user
    @page = "suggestions"
    @suggestions = User.select{ |user| current_user.unrelated?(user) }
  end

  def outgoing
    @user = current_user
    @page = "outgoing"
    @outgoing = User.select{ |user| current_user.pending_request?(user) }
  end

  def requests
    @user = current_user
    @page = "request"
    @requests = User.select{ |user| current_user.awaiting_confirm?(user) }
  end

  def show
    @page = "profile"
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:user).order(created_at: :desc)
    @comment = Comment.new
    @friend_ids = current_user.friend_ids
  end

#  def my_friends
#    @friends = current_user.friends
#  end

  def friends
    @page = "friend"
    if params[:id] == current_user.id
      redirect_to "/friends"
    elsif params[:id] == 0
      @user = current_user
      @friends = current_user.friends
    else
      @user = User.find(params[:id])
      @friends = @user.friends
    end
  end

  def photos
    if params[:id] == current_user.id
      redirect_to "/photos"
    elsif params[:id] == 0
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end

  def add_avatar
    @user = current_user
  end

  def update
      if current_user.update_attributes(user_params)
        redirect_to current_user
      else
        @user = current_user
        redirect_to add_avatar_url
      end
  end

  def sign_in
  end


  private
    def user_params
      params.require(:user).permit(:avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_confirm_request.html.erb
<div class="user_row", id="confirm_request_row_<%= user.id %>">

  <div id="confirm_request_form_<%= user.id %>">
    <% if current_user.friend?(user) %>
        <%= render partial: 'undo_confirm_request', locals: {user: user} %>
    <% else %>
      <%= render partial: 'confirming_request', locals: {user: user} %>
    <% end %>
  </div>

</div>

app/views/users/_confirming_request.html.erb
<table>
    <tr>
      <% unless @page == "profile" %>
        <td>
          <div class="friend_request_avatar"><%= render 'shared/avatar', user: user %><div>
        </td>
      <% end %>

    <td>
      <% if @page != "profile" %>
        <div><%= link_to user.username, user, class:"username" %></div>
      <% end %>

      Friend request received
      <table>
        <tr>
          <td style="padding: 0px 10px">
            <%= form_for(current_user.friendships.build, remote: true) do |f| %>
              <div><%= hidden_field_tag :friend_id, user.id %></div>
              <div><%= hidden_field_tag :page, @page %></div>
              <%= f.submit "Accept", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td>
            <%= form_for(current_user.passive_requests.find_by(requestor_id: user.id), remote: true) do |f| %>
             <div><%= hidden_field_tag :page, @page %></div>
              <%= f.submit "Deny", class: "btn btn-secondary" %>
            <% end %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/users/_friend_button_together.html.erb
<div class="", id="profile_page_friend_button_<%= user.id %>">
  <% unless user == current_user %>
    <% if current_user.friend?(user) %>
      <%= render partial: "unfriend", locals: { user: user }%>
    <% elsif current_user.awaiting_confirm?(user) %>
      <%= render partial: "confirm_request", locals: { user: user }%>
    <% else %>
      <%= render partial: "request", locals: { user: user } %>
    <% end %>
  <% end %>
</div>

app/views/users/_logged_in_profile_menu.html.erb
<br>
<div class="profile_menu">
    <% if current_user == @user %>
      <div><%= link_to "Photos", photos_path, class: "photos_link" %></div>
      <div><%= link_to "Friends", friends_path %></div>
      <div><%= link_to "Incoming Requests", requests_path %></div>
      <div><%= link_to "Outgoing Requests", outgoing_path %></div>
      <div><%= link_to "Add More Friends?", suggestions_path %></div>
    <% else %>
      <div><%= link_to "Photos", photos_user_path, class: "photos_link" %></div>
      <div><%= link_to "Friends", friends_user_path(@user) %></div>
    <% end %>
</div>
</br>

app/views/users/_request.html.erb
<div class="user_row" id="request_row_<%= user.id %>">

    <div id="request_form_<%= user.id %>">
      <% if current_user.pending_request?(user) %>
        <%= render partial: 'undo_send_request', locals: {user: user} %>
      <% else %>
        <%= render partial: 'send_request', locals: {user: user}  %>
      <% end %>
    </div>

</div>

app/views/users/_undo_confirm_request.html.erb
<table>
    <tr>
      <% unless @page == "profile" %>
        <td>
          <div class="friend_request_avatar"><%= render 'shared/avatar', user: user %><div>
        </td>
      <% end %>

    <td>
      <% if @page != "profile" %>
        <div><%= link_to user.username, user, class:"username" %></div>
      <% end %>

      Request accepted
      <%= form_for(current_user.friendships.find_by(friend_id: user.id), remote: true) do |f| %>
        <div><%= hidden_field_tag :requestor_id, user.id %></div>
        <%= f.submit "Undo", class: "btn btn-secondary" %>
      <% end %>

    </td>
  </tr>
</table>

app/views/users/_undo_send_request.html.erb
<table>
    <tr>
      <% unless @page == "profile" %>
        <td>
          <div class="friend_request_avatar"><%= render 'shared/avatar', user: user %><div>
        </td>
      <% end %>

    <td>
      <% if @page != "profile" %>
          <div><%= link_to user.username, user, class:"username" %></div>
      <% end %>

      <p>Request sent</p>

      <%= form_for(current_user.active_requests.find_by(receiver_id: user.id),
                   html: { method: :delete },
                   remote: true) do |f| %>
        <div><%= hidden_field_tag :page, @page %></div>
        <%= f.submit "Undo", class: "btn btn-secondary" %>
      <% end %>
    </td>
  </tr>
</table>

app/views/users/_unfriend.html.erb
<div class="user_row", id="friend_row_<%= user.id %>">
  <table>
      <tr>
        <% unless @page == "profile" %>
          <td>
            <div class="friend_request_avatar"><%= render 'shared/avatar', user: user %><div>
          </td>
        <% end %>

      <td>
      <% if @page != "profile" %>
          <%= link_to user.username, user, class: "username" %>
      <% end %>

      <div id="unfriend_form_<%= user.id %>">
        <% if params[:id] == 0 or @page == "profile" or @page == "friend" %>
          <%= form_for(current_user.friendships.find_by(friend_id: user.id),
                       html: { method: :delete },
                       remote: true) do |f| %>
            <div><%= hidden_field_tag :page, @page %></div>
            <%= f.submit "Unfriend", class: "btn btn-secondary" %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
</table>


</div>

app/views/users/friends.html.erb
<% if params[:id] == 0 %>
  <h1>Friends</h1>
  <%= render 'logged_in_profile_menu' %>
<%else %>
  <h1><%= link_to @user.username, @user %></h1>
  <%= render 'logged_in_profile_menu'%>
  <h3>Friends</h3>
<% end %>


<% if @friends[0].nil? %>
  <% if params[:id] == 0 %>
    You don't have friends yet. <%= link_to "Add More Friends?", suggestions_path %></div>
  <% else %>
    This person has no friends :(
  <% end %>
<% else %>
<ul class="friends">
  <%= render partial: "friend_button_together", collection: @friends, as: :user %>
</ul>
<% end %>

app/views/users/outgoing.html.erb
<h1>Outgoing Friend Requests</h1>
<%= render 'logged_in_profile_menu' %>

<ul class="outgoing">
  <%= render partial: "request", collection: @outgoing, as: :user %>
</ul>

app/views/users/photos.html.erb
<% if params[:id] == 0 %>
  <h1>Photos</h1>
  <%= render 'logged_in_profile_menu' %>
<%else %>
  <h1><%= link_to @user.username, @user %></h1>
  <%= render 'logged_in_profile_menu'%>
  <h3>Photos</h3>
<% end %>

<div class="picture_div">
  <%  @user.post_attachments.each do |att| %>
    <% unless att.picture.blank? %>
      <div class="thumbnails">
        <%= link_to image_tag(att.picture.url(:medium), class: "picture"), att.post %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/requests.html.erb
<h1>Friend Requests</h1>
<%= render 'logged_in_profile_menu' %>

<ul class="requests">
  <%= render partial: "confirm_request", collection: @requests, as: :user %>
</ul>

app/views/users/show.html.erb
<div class="profile_name_avatar">
  <div class="avatar">
    <%= render 'shared/avatar', user: current_user %>
  </div>
  <h1><%= @user.username %></h1>
</div>
<br>

<% if current_user == @user %>
  <%= link_to "Change avatar", add_avatar_path if (@user.avatar.present? or @user.fb_avatar )%>
  <%= link_to "Add avatar", add_avatar_path if !@user.avatar.present? and !@user.fb_avatar %>
<% end %>

<div class="profile_page_friend_button" >
<%= render 'friend_button_together', user: @user %>
</div>
<%= render 'logged_in_profile_menu'%>


<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <%= render partial: "posts/post", collection: @posts, as: :post %>
  </div>

</div>

app/views/users/suggestions.html.erb
<h1>Suggestions</h1>
<%= render 'logged_in_profile_menu' %>

<ul class="suggestions">
  <%= render partial: "request", collection: @suggestions, as: :user %>
</ul>