config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/friends', to: 'users#friends' , id: 0
  get '/requests', to: 'users#requests'
  get '/outgoing', to: 'users#outgoing'
  get '/suggestions', to: 'users#suggestions'
  get '/add_avatar', to: 'users#add_avatar'
  get '/photos', to: 'users#photos', id: 0
  resources :users, only: [:show, :update] do
    member do
      get :friends
      get :photos
    end
#    collection do
#      get :suggestions
#    end
  end
  resources :friendships, only: [:create, :destroy, :update]
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments, only: [:create, :destroy, :update, :edit] do
    member do
      get :show_edit_comment_window, as: 'window'
    end
  end
  get 'show_edit_comment_window', to: 'comments#show_edit_comment_window'
  resources :likes, only: [:create, :destroy]
  resources :post_attachments
  get '/sign_in', to: 'users#sign_in'
  get '/get_comments', to: 'comments#get_comments'
  get '/newest', to: 'static_pages#newest'
end

app/views/shared/_avatar.html.erb
<%# cache [ "u#{user.id}-av", user.updated_at.to_i ] do %>
  <% user= OpenStruct.new(user) if user.is_a? Hash %>
  <% if user.avatar_present? %>
    <%= image_tag user.avatar_url_thumb, class: "avatar_thumb" %>
  <% elsif user.fb_avatar %>
    <%= image_tag user.fb_avatar, class: "avatar_thumb" %>
  <% else %>
    <%= image_tag "thumb/default_avatar.jpg", class: "avatar_thumb" %>
  <% end %>
<%# end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <% object.errors.full_messages.each do |msg| %>
      <p style="color: red;"><%= msg %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_toggle_menu.html.erb
<% obj_name = obj.class.name.downcase %>
<% obj_name = "post" if obj_name == "openstruct" %>

<div class="dropdown <%= obj_name %>_nav">
    <button class="btn dropdown-toggle <%= obj_name %>_edit_button" type="button" data-toggle="dropdown">
    <span class="caret"></span></button>
    <ul class="dropdown-menu dropdown-menu-right" id="<%= obj_name %>_menu">
        <% if obj_name == "post" %>
            <li><%= link_to "Edit post", edit_post_path(obj.id) %></li>
            <li><%= link_to "Delete post", post_path(obj.id), method: :delete, data: { confirm: "are your sure?" } %></li>
        <% elsif obj_name == "comment" %>
            <li><%= link_to "Edit", show_edit_comment_window_path(id: obj.id), class: "btn btn-block edit_comment_button", remote: true %></li>
            <li><%= link_to "Delete", comment_path(obj.id), method: :delete, class: "btn btn-block delete_comment_button", remote: true %></li>
        <% end %>
    </ul>
</div>

app/views/shared/_updated_time.html.erb
<% if obj.created_at != obj.updated_at %>
    <p class="updated_at">Updated <%= time_ago_in_words(obj.updated_at) %> ago</p>
<% else %>
    <p class="created_at"><%= time_ago_in_words(obj.created_at) %> ago</p>
<% end %>