config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/friends', to: 'users#friends' , id: 0
  get '/requests', to: 'users#requests'
  get '/outgoing', to: 'users#outgoing'
  get '/suggestions', to: 'users#suggestions'
  get '/add_avatar', to: 'users#add_avatar'
  get '/photos', to: 'users#photos', id: 0
  resources :users, only: [:show, :update] do
    member do
      get :friends
      get :photos
    end
#    collection do
#      get :suggestions
#    end
  end
  resources :friendships, only: [:create, :destroy, :update]
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments, only: [:create, :destroy, :update, :edit] do
    member do
      get :show_edit_comment_window, as: 'window'
    end
  end
  get 'show_edit_comment_window', to: 'comments#show_edit_comment_window'
  resources :likes, only: [:create, :destroy]
  resources :post_attachments
  get '/sign_in', to: 'users#sign_in'
  get '/get_comments', to: 'comments#get_comments'
  get '/newest', to: 'static_pages#newest'
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  include ApplicationHelper

  mount_uploader :picture, PictureUploader
  belongs_to :post, touch: true
  has_attached_file :picture, :styles => {
      :thumb => "100x100#",
      :small  => "300x300#",
      :medium => "400x400#" }
  validates_attachment :picture, presence: true, size: { in: 0..5.megabytes }, content_type: { content_type: /\Aimage/ }
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]
  before_action :post_attachment_correct_user, only: [:edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @page = "edit_post"
    @post_attachment.destroy
    redirect_to request.referrer || root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :picture)
    end

    def post_attachment_correct_user
      post_attachment = current_user.post_attachments.find(params[:id])
      redirect_to root_url if post_attachment.nil?
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= form_with(model: post_attachment, local: true) do |form| %>
  <% if post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :post_attachment_post_id %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :post_attachment_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.picture %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @post_attachment.picture %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>