config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/friends', to: 'users#friends' , id: 0
  get '/requests', to: 'users#requests'
  get '/outgoing', to: 'users#outgoing'
  get '/suggestions', to: 'users#suggestions'
  get '/add_avatar', to: 'users#add_avatar'
  get '/photos', to: 'users#photos', id: 0
  resources :users, only: [:show, :update] do
    member do
      get :friends
      get :photos
    end
#    collection do
#      get :suggestions
#    end
  end
  resources :friendships, only: [:create, :destroy, :update]
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments, only: [:create, :destroy, :update, :edit] do
    member do
      get :show_edit_comment_window, as: 'window'
    end
  end
  get 'show_edit_comment_window', to: 'comments#show_edit_comment_window'
  resources :likes, only: [:create, :destroy]
  resources :post_attachments
  get '/sign_in', to: 'users#sign_in'
  get '/get_comments', to: 'comments#get_comments'
  get '/newest', to: 'static_pages#newest'
end

app/models/post.rb
class Post < ApplicationRecord
  include ApplicationHelper

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :liked_user_relationships, class_name:  "Like",
                                     dependent:   :destroy
  has_many :liked_users, through: :liked_user_relationships, source: :user

  has_many :post_attachments, dependent:   :destroy
  accepts_nested_attributes_for :post_attachments

  #default_scope -> { order(created_at: :desc) }
  validates :user, presence: true
  #validates :content, allow_blank: true
  validate :text_or_photos


  after_create :add_post_to_newest_list
  #before_validation(on: :update) { cache_updated_at }
  #before_update :remove_post_from_redis
  #after_update :add_post_to_newest_list
  after_destroy :remove_post_from_newest_list

  def liked_by?(user)
    !liked_user_relationships.find_by(user_id: user.id).nil?
  end

  def liked_friends(user)
    liked_users.all.select{ |liked_user| user.friend?(liked_user) } #don't know why but need to add #all to liked_user to return ALl liked_users, else would be truncated
  end

  def liked_names
    liked_users.pluck(:username) 
  end

  def text_or_photos
    if content.strip.empty? and post_attachments.blank?
      errors.add(:content, "cannot be blank unless photos are added")
    end
  end

  # def add_post_to_redis
  #   add_record_to_redis(self)
  # end

  # def cache_updated_at #this is necessary because it is executed after update, causing the score, i.e. updated_at to be changed
  #   @updated_at = self.updated_at.to_i.to_s
  # end

  # def remove_post_from_redis_before_update
  #   remove_record_from_redis(self, @updated_at)
  # end

  # def remove_post_from_redis
  #   remove_record_from_redis(self)
  # end

  def add_post_to_newest_list
    $redis.lpush("newest_post_ids", id)
    $redis.ltrim("newest_post_ids", 0, 99)
    RedisWorker.perform_async(id)
  end

  def remove_post_from_newest_list
    $redis.lrem("newest_post_ids", -1, id)
    $redis.zremrangebyscore("newest_posts", id, id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, except: [:show]
  before_action :post_correct_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to request.referrer || root_url
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    if request.referrer.to_s.include?(@post.id.to_s)
      redirect_to root_url
    else
      redirect_to request.referrer || root_url
    end
  end

  def edit
    if !request.referrer.to_s.include?("edit")
      store_location
    end
    @page = "edit_post"
  end

  def update
    if @post.update_attributes(post_params)
      redirect_back_or(root_url)
    else
      @page = "edit_post"
      render 'edit'
    end
  end

  def show
    store_location_before_signed_in
    @page = "individual_post"
    @post = Post.includes(:user, :liked_users).find_by(id: params[:id])
    @comment = Comment.new
    @friend_ids = current_user.friend_ids if current_user
    if @post.nil?
      render 'not_found'
    end
  end

  def not_found
  end

  private
    def post_params
      #params.require(:post).permit(:content, post_attachment_attributes: [:id, :post_id, :picture])
      params.require(:post).permit(:content, post_attachments_attributes: ["picture", "@original_filename", "@content_type", "@headers", "_destroy", "id"])
    end

    def post_correct_user
      @post = current_user.posts.find(params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def like_sentence(user, post, friend_ids = nil)
        common_ids = friend_ids & post.liked_user_ids 
        common_ids_index = common_ids.map{|id| post.liked_user_ids.rindex(id)}
        names = post.liked_names
    
        arr = [] 
        arr << "You" if post.liked_user_ids.include?(user.id) 
        arr << names[common_ids_index[0]] if common_ids_index[0] 
        arr << names[common_ids_index[1]] if common_ids_index[1] 
    
        others_count = post.liked_user_ids.count - arr.count 
        arr << others_count.to_s + " " + "other".pluralize(others_count) if others_count > 0
        (arr.count > 1) ? (arr.first(arr.size - 1).join(", ") + " and " + arr[-1]) : arr[0].to_s
    end
end

app/views/posts/_attachments.html.erb
<% if post.post_attachments[0] %>
    <div class="picture_div">
        <% post.post_attachments.each do |att| %>
        <% att = OpenStruct.new(att) if att['picture_url'] %>
        <span><%= image_tag att.picture_url, class: "picture" %></span>
        <% end %>
    </div>
<% end %>

app/views/posts/_expand_comment_button.html.erb
<% if current_user %>
    <div class="expand_comment_button" id="expand_comment_button_<%= post.id %>" disableonclick = "btnFunc('hey', this)" data-id="<%= post.id %>">
        <span class="glyphicon glyphicon-comment"></span> 
        <a class="btn">Comment</a>
    </div>
<% else %>
    <div class="expand_comment_button">
        <span class="glyphicon glyphicon-comment"></span> 
        <%= link_to "Comment", sign_in_path, class: "btn" %>
    </div>
<% end %>

app/views/posts/_like_button.html.erb
<div class="like_button_<%= post.id %>">
  <% if current_user %>
      <% if !post.liked_user_ids.include? current_user.id %>
          <% cache [post.id, "like_btn"] do %>
              <span class="glyphicon glyphicon-thumbs-up"></span>
              <%= link_to "Like", likes_path(post_id: post.id), class: "btn", id:"like_submit_button", method: :post, remote: true %>
          <% end %>
      <% else %>
          <% cache [post.id, "unlike-btn"] do %>
              <span class="glyphicon glyphicon-thumbs-up unlike-glyph"></span>
              <%= link_to "Unlike", like_path(id: 1, post_id: post.id), class: "btn", id:"unlike_submit_button", method: :delete, remote: true %>
          <% end %>
      <% end %>
  <% else %>
      <% cache "like_btn_not_login" do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <div class="btn btn-block" id="like_submit_button"><%= link_to "Like", sign_in_path %></div>
      <% end %>
  <% end %>
</div>

app/views/posts/_like_count_sentence.html.erb
<% if current_user %>
  <% if post.liked_user_ids.count != 0 %>
    <span class="glyphicon glyphicon-thumbs-up like_counter"></span>
    <%= like_sentence(current_user, post, current_user.friend_ids) %>
  <% end %> 
<% elsif post.liked_user_ids.count > 0 %>
  <span class="glyphicon glyphicon-thumbs-up like_counter"></span>
  <%= post.liked_user_ids.count %>
<% end %>

app/views/posts/_post.html.erb
<% require 'ostruct' %>
<% post = JSON.parse(post) if post.is_a? String %>
<% post = OpenStruct.new(post) if post.is_a? Hash %>

<div class="post", id="post_<%= post.id %>">
  <% if current_user and current_user.id == post.user_id %>
    <%# cache "p#{post.id}-tog" do %>
      <%= render 'shared/toggle_menu', obj: post %>
    <%# end %>
  <% end %>

  <%# cache [ "u#{post.user.id}-pinfo", post.user.updated_at.to_i ] do %>
  <div class="post-info">
    <div class="avatar"><%= render 'shared/avatar', user: post.user %></div>
    <div class="post_user_info">
      <%= link_to post.user['username'], user_path(post.user_id), class: "username" %>
  <%# end %>
  
  <%# cache post do %>
  <%# Rails by default generates this %>
  <%# cache "posts/#{post.id}-#{post.updated_at.strftime('%Y%m%d%H%M%S%N')[0..-4]}" do %> 

      <%= render 'shared/updated_time', obj: post %>
    </div>
  </div>

  <div class="clear"></div>
  <span class="post_content"><%= post.content %></span>
  <%= render 'posts/attachments', post: post %>
<%# end %>

  <% unless @page == "individual_post" %>
    <div class="post_link"><%= link_to "Full post", post_path(post.id) %></div>
  <% end %>

  <div class="like_counts_<%= post.id %>">
    <%= render "posts/like_count_sentence", post: post, names: post['liked_user_names']  %>
  </div>
 
  <div class="post_footer">
    <%= render 'posts/post_footer', post: post %>
  </div>

  <% if !current_user.nil? %>
    <div class="comment_section" id="comment_section_<%= post.id %>" style="display:none;" ></div>
  <% end %>

</div>

<% if false %>
<script>
btnFunc = function(text, elem) {
  console.log($(elem))
  alert(text);
  $(elem).prop('onclick',null).off('click', 'btnFunc');
}
</script>
<% end %>

app/views/posts/_post_footer.html.erb
<% if false %> <%# After trying, rendering partials had a huge cost on performance thus I switched back %>
    <table><tr>
        <td><%= render 'posts/like_button', post: post %></td>
        <td><%= render 'posts/expand_comment_button', post: post %></td>
        <td><%= render 'posts/share_button', post: post %></td>
    </tr></table>
<% end %>

<%  liked = current_user ? (post.liked_user_ids.include? current_user.id) : false %>
<%# cache [ "p#{post.id}-foot", liked, current_user.nil? ]do %>
<table><tr>
    <td>
        <div class="like_button_<%= post.id %>">
        <% if current_user %>
            <% if !liked %>
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <%= link_to "Like", likes_path(post_id: post.id), class: "btn", id:"like_submit_button", method: :post, remote: true %>
            <% else %>
                <span class="glyphicon glyphicon-thumbs-up unlike-glyph"></span>
                <%= link_to "Unlike", like_path(id: 1, post_id: post.id), class: "btn", id:"unlike_submit_button", method: :delete, remote: true %>
            <% end %>
        <% else %>
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <div class="btn btn-block" id="like_submit_button"><%= link_to "Like", sign_in_path %></div>
        <% end %>
        </div>
    </td>

    <td>
        <% if current_user %>
            <div class="expand_comment_button" id="expand_comment_button_<%= post.id %>" disableonclick = "btnFunc('hey', this)" data-id="<%= post.id %>">
                <span class="glyphicon glyphicon-comment"></span> 
                <a class="btn">Comment</a>
            </div
        <% else %>
            <div class="expand_comment_button">
                <span class="glyphicon glyphicon-comment"></span> 
                <%= link_to "Comment", sign_in_path, class: "btn" %>
            </div>
        <% end %>
    </td>


    <td>
        <div class="share_button">
            <span class="glyphicon glyphicon-share-alt"></span>
            <%= link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?u=warm-plains-72294.herokuapp.com/posts/#{post.id}", html_options= {target: "_blank", class: "btn"} %>
        </div>
    </td>

</tr></table>
<%# end %>

app/views/posts/_post_footer_loggedin.html.erb
<% liked = post.liked_user_ids.include? current_user.id %>

<% cache [ "p#{post.id}-foot", liked ] do %>
<table><tr>
    <td>
        <div class="like_button_<%= post.id %>">
            <% if !liked %>
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <%= link_to "Like", likes_path(post_id: post.id), class: "btn", id:"like_submit_button", method: :post, remote: true %>
            <% else %>
                    <span class="glyphicon glyphicon-thumbs-up unlike-glyph"></span>
                    <%= link_to "Unlike", like_path(id: 1, post_id: post.id), class: "btn", id:"unlike_submit_button", method: :delete, remote: true %>
            <% end %>
        </div>
    </td>

    <td>
        <div class="expand_comment_button" id="expand_comment_button_<%= post.id %>" disableonclick = "btnFunc('hey', this)" data-id="<%= post.id %>">
            <span class="glyphicon glyphicon-comment"></span> 
            <a class="btn">Comment</a>
        </div>
    </td>

    <td>
        <div class="share_button">
            <span class="glyphicon glyphicon-share-alt"></span>
            <%= link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?u=warm-plains-72294.herokuapp.com/posts/#{post.id}", html_options= {target: "_blank", class: "btn"} %>
        </div>
    </td>

</tr></table>
<% end %>

app/views/posts/_post_footer_unloggedin.html.erb
<% cache "p#{post.id}-foot-unlog"  do %>
<table><tr>
    <td>
        <div class="like_button_<%= post.id %>">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <div class="btn btn-block" id="like_submit_button"><%= link_to "Like", sign_in_path %></div>
        </div>
    </td>

    <td>
        <div class="expand_comment_button">
            <span class="glyphicon glyphicon-comment"></span> 
            <%= link_to "Comment", sign_in_path, class: "btn" %>
        </div>
    </td>


    <td>
        <div class="share_button">
            <span class="glyphicon glyphicon-share-alt"></span>
            <%= link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?u=warm-plains-72294.herokuapp.com/posts/#{post.id}", html_options= {target: "_blank", class: "btn"} %>
        </div>
    </td>

</tr></table>
<% end %>

app/views/posts/_post_form.html.erb
<% if @page == "edit_post" %>
  <div style="float: right">
    <%= link_to "Delete post", post_path(@post.id), method: :delete, class: "btn btn-primary" %>
  </div>
<% end %>

<div class="logged-in-user-info">
  <div class="avatar">
    <%= render 'shared/avatar', user: current_user %>
  </div>
  <div class="current_user_username"><%= current_user.username %></div>
</div>

<div class="post-form">
  <%= form_for(@post, :html => { :multipart => true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, cols: "1000", rows: "6", placeholder: "Compose new post...", class: "form-control" %>
    </div>


    <div class="row">
      <%= f.fields_for :post_attachments,  @post.post_attachments.build do |p| %>
        <div class="col-xs-6">
          <%= f.file_field :picture, :multiple => true, name: "post[post_attachments_attributes][][picture]",
              class: "filestyle upload_file", :'data-input' => "false", :'iconName' => "glyphicon glyphicon-folder-open",
              :'data-buttonName' => "btn btn-primary", :'data-buttonText' => "Add Photos",
              :'data-buttonBefore' => "true", accept: 'image/jpeg,image/gif,image/png' %>
        </div>
      <% end %>

      <div class="col-xs-6">
        <%= f.submit "Post", class: "btn btn-primary post_button"%>
      </div>
    </div>
  <% end %>
</div>


<% if @post.post_attachments %>
  <br>
  <div class="picture_div">
    <%  @post.post_attachments.each do |att| %>
      <% unless att.picture.blank? %>
        <div class="thumbnails">
          <%= image_tag(att.picture.url(:thumb).html_safe, class: "picture") %>
          <%= link_to "Delete Photo", att, method: :delete %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>


<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/_share_button.html.erb
<div class="share_button">
    <span class="glyphicon glyphicon-share-alt"></span>
    <%= link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?u=warm-plains-72294.herokuapp.com/posts/#{post.id}", html_options= {target: "_blank", class: "btn"} %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8">
      <%= render 'posts/post_form' %>
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-8">
      <%= render 'posts/post_form' %>
    </div>
    <div class="col-xs-2">
    </div>
  </div>
</div>

app/views/posts/not_found.html.erb
The post is no longer available

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-8">
    <%= render @post %>
  </div>
  <div class="col-lg-4"></div>
</div>